# Generated by Django 2.2.3 on 2019-10-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0003_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
