# Generated by Django 2.2.3 on 2019-10-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainShop', '0007_auto_20191018_2238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Orders', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderupdate',
            options={'verbose_name': 'OrderUpdates', 'verbose_name_plural': 'OrderUpdates'},
        ),
    ]
